[ui]
sort-thread-siblings=true
threading-enabled=true
force-client-threads=true
show-thread-context=true

[filters]
subject,~^\[(pve|pbs|pdm|pmg|yew)-devel\] \[=delta - | colorize
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=! html
.headers=colorize
